### PR TITLE
removed return statements from thimbl.rb

### PR DESCRIPTION
**Pull request by buddhamagnet**
Hi there (I'm a friend of dk and a ruby developer would love to assist). Have removed the return keyword from the methods in thimbl.rb - as ruby will return the last statement in any case, less to type/maintain!

### CODE REVIEW

**Comment by fguillen** [comment]
Hi Dave, this modifications are just a matter of taste. I like the explicit `return` when the method has more than one line.

I really appreciate your support.

**Comment by buddhamagnet** [comment]
No worries, I thought that would be the case. Would love to be involved when I have the time so expect the occasional pull request!

**Comment by buddhamagnet** [comment]
...y mucho gusto. Hablo un poco espanol y voy a moverme a Espana (probablemente Marbella) en un cierto punto.

**Comment by fguillen** [comment]
:), Mucho gusto!

**Pull request closed without merging**
